### ISSUE TITLE
TypeScript import not working with "noImplicitAny" option set

### ISSUE THREAD

**Issue by rhuitl** [Hypercubed/mini-signals#12]
Hi, I was trying the latest revision with TypeScript support but get this error when trying to import:
```
(4,29): error TS7016: Could not find a declaration file for module 'mini-signals'. '/path/node_modules/mini-signals/lib/mini-signals.js' implicitly has an 'any' type.
```
My tsconfig.json has the "noImplicitAny" option set:
```
{
	"compilerOptions": {
		"sourceMap": true,
		"noImplicitAny": true,
		"module": "commonjs",
		"target": "es5",
		"allowJs": false
	}
}
```

**Comment by easyfuckingpeasy** [comment]
Seems like the typings are npm-ignored. In addition to that, there seem to be issues importing using commonjs. I made some changes in a fork (easyfuckingpeasy/mini-signals#98a682d), could you try them out? Import by doing either `import MiniSignal = require('mini-signals')` or `import * as MiniSignal from 'mini-signals'`.

**Comment by rhuitl** [comment]
Yes, that made it work, thanks! I was using
```
import * as MiniSignal from "mini-signals";
```
before and it was working as long as noImplicitAny=false (with Webpack + tsconfig module option = "commonjs").

**Comment by Hypercubed** [comment]
Thanks for the input @easyfuckingpeasy , sorry I've not been much help myself.  I haven't tried using `MiniSignals` in typescript.  :(

**Comment by easyfuckingpeasy** [comment]
No problem, I made the typings so I feel it's my obligation to make sure they work :)

Should I make a pull request with the changes?
