### ISSUE TITLE
Error with jsnext:main in package.json

### ISSUE THREAD

**Issue by accnops** [Hypercubed/mini-signals#16]
I don't know why, but I had to change `"jsnext:main": "src/mini-signals.js",` to `"jsnext:main": "lib/mini-signals.js",` in package.json so it would work with webpack. Any idea why?

As reference for my fellow webpack users, the error I got was the following:

    ERROR in 3.a3f47f38d1b31420e78e.chunk.js from UglifyJs
    Unexpected token: name (MiniSignalBinding) [3.a3f47f38d1b31420e78e.chunk.js:6304,6]

**Comment by darkowic** [comment]
Confirm that. Here is similar issue - https://github.com/vesparny/brcast/issues/7
The jsnext should point to the same file as `module`
Here is more about it https://github.com/shuhei/material-colors/issues/13#issuecomment-270462099

**Comment by vesparny** [comment]
fixed in `brcast@3.0.1`

**Comment by darkowic** [comment]
@Hypercubed what about this issue? It's really important

**Comment by darkowic** [comment]
For anyone coming here after this time: `jsnext:main` is deprecated. Just remove the `jsnext:main` from your webpack `mainFields`
