### ISSUE TITLE
Add priority

### ISSUE THREAD

**Issue by Hypercubed** [Hypercubed/mini-signals#2]
As discussed [here](https://github.com/Hypercubed/mini-signals/issues/1#issuecomment-141421037) add `addBefore` and `addAfter`.

**Comment by PierBover** [comment]
Hey @Hypercubed have you started implementing this?

**Comment by Hypercubed** [comment]
No I have not started.  I personally haven't had a need for this feature.  PRs are welcome.

**Comment by vlucendo** [comment]
yeah it would be nice to have this option
