### ISSUE TITLE
API suggestion

### ISSUE THREAD

**Issue by prettymuchbryce** [Hypercubed/mini-signals#4]
Hello. This is a neat little library. I have a tiny API suggestion. What do you think about renaming the `detach()` method to `remove()`. I tend to think of "detach" as being an antonym for "attach" rather than "add".

**Comment by Hypercubed** [comment]
Hello, thank you for your, very reasonable, suggestion.  However, I used the word `detach` here to avoid confusion with `remove` in the js-signals API.  In fact if you think about it `add` is short for `addListener`.  In the mini-signals v1.0 API the antonym method `removeListener` is deprecated...  in its place we can `detach` signal bindings.
