### ISSUE TITLE
copy listeners before dispatch

### ISSUE THREAD

**Issue by nshen** [Hypercubed/mini-signals#8]
I think its better to copy all listeners before execute _fun in dispatch method.
it's common to add or detach listener during dispatch.

**Comment by Hypercubed** [comment]
Can you give an example of where this comes into play with mini-signals?  Mini signals is a linked list.  If a listener added or detached during a dispatch it should only matter if the listener is before or after the current.

**Comment by Hypercubed** [comment]
Realistically there is no reasonable way to copy the listeners before dispatch.  This would likely defeat the purpose of using a linked list.  If you still think this is an issue please reopen with an example of where this causes a problem.  Thanks.
