### ISSUE TITLE
suspend the signal ?

### ISSUE THREAD

**Issue by ncou** [Hypercubed/mini-signals#9]
Hi,

First very nice library :)
Is there a way to "suspend" the signal propagation ? 
something like the "active" propertie in js-signal.
I need to suspend the signals before a loop and reactivate it at the end of the loop.

any insight ?

Thank you and keep up the good work.

**Comment by Hypercubed** [comment]
Currently no support.  Is the idea that the signal as a whole is shut down, or just individual listeners?

**Comment by ncou** [comment]
just shut down "individual listener".

For example you have a "create signal" listener, but before a loop you want to desactivate it (because the loop will create X objects), and once the loop is finished you want to reactivated it.
